### ISSUE TITLE
[Docs] add community guidelines

### ISSUE THREAD

**Issue by nantonel** [1oly/AeroAcoustics.jl#11]
Could you please add some text addressing the following?

> Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

Issue opened as part of review: https://github.com/openjournals/joss-reviews/issues/6390

**Comment by 1oly** [comment]
Hi @nantonel Thanks for the suggestion. Just pushed this to master:

## Community and contributions
Any question regarding the installation, use or extension of the code can be posted in the [Github issue tracker](https://github.com/1oly/AeroAcoustics.jl/issues).
If you want to add an new algorithm, you can fork this package and start developing your code and test it. If you wish to contribute to the general development, you can look for open issues or reach out to discuss further. Contributions are very welcome!
