### ISSUE TITLE
functionality to generate cross-spectral matrix?

### ISSUE THREAD

**Issue by thejasvibr** [1oly/AeroAcoustics.jl#12]
The example notebook loads an HDF5 file with a cross-spectral matrix, and then begin the process of comparing/testing the performance of various beamforming algorithms. 

As a naive user beginning to use the tool, I see one 'missing step', which is the conversion from raw audio to cross-spectral matrix (CSM). 
Maybe the CSM is a natural starting point for the aeroacoustics community because of experimental/equipment conventions. Speaking from my own experience with bioacoustics, and potentially most other use-cases I would expect a multichannel audio file to be the starting point for any analyses. 

A function/ality to load raw WAV files or multi-channel audio data and convert it to a CSM would essentially reduce the barrier to entry for 1) anyone new to Julia, but more importantly 2) new to AeroAcoustics! For example, seeing that the Julia Notebook already has the code to load a wav file and move onto beamforming means that any user can freely substitute the audio file path, and become a dedicated 'AeroAcoustics.jl' user :). 

Again, this is only a suggestion. I say this without any further knowledge of the Julia ecosystem, the ability to handle multichannel audio as input could be a small investment with big impact on the user-end.

**Comment by 1oly** [comment]
Hi @thejasvibr. This is a very good suggestion, thanks. The functionality is already included, albeit [documented](https://1oly.github.io/AeroAcoustics.jl/dev/reference/#AeroAcoustics.csm-Union{Tuple{AbstractArray{T,%20N}%20where%20N},%20Tuple{T}}%20where%20T%3C:AbstractFloat) simplistic. I think, that showcasing how to import from, e.g., WAV files would be a good addition to the docs.
