### ISSUE TITLE
no example data in repo to run notebook

### ISSUE THREAD

**Issue by thejasvibr** [1oly/AeroAcoustics.jl#6]
As I try to run Cell 2 of the example notebook, this error pops up. 
Also, having looked into the repo as it stands - doesn't seem like the data files are in version control.

![image](https://github.com/1oly/AeroAcoustics.jl/assets/12443569/291bd7a9-c20d-4776-a324-0f1a61196fb1)

- related to openjournals/joss-reviews#6390

**Comment by 1oly** [comment]
Thanks for the fresh eyes on my package @thejasvibr 👍 I’m on vacation and will be back in a week and look into your issue.

**Comment by 1oly** [comment]
Hi @thejasvibr ! Thanks for waiting. The data for the example is first downloaded from an external repo when you run the tests. This is not documented, I'm sorry about that. I will update the README and the example notebook to reflect this. If you want to test it out you should invoke the julia package manager by `]` (changing the prompt to `pkg>`) and write:
```
pkg> test AeroAcoustics
```
Then the data is downloaded and should subsequently be available for the example script...
This should also somewhat address your other issue about tests. I will working on a better documentation of this in the coming week.

**Comment by 1oly** [comment]
Hi again @thejasvibr, could I ask you to report back about the above suggestion, when time permits? If it works, I will add the instructions to the README and script.

**Comment by thejasvibr** [comment]
Hi @1oly - no change in error message. This is after running the tests as suggested in the post above.

**Comment by 1oly** [comment]
Hi @thejasvibr Thank you. I completely agree, and will find an alternative solution about the data. But for now, I'm hoping to get the current script running, since there might be other issues there to be found. 

Did the tests complete? 
If yes, then you were in fact able to download the file, but it's simply not found by the script.

**Comment by thejasvibr** [comment]
The tests passed successfully, so I guess the data isn't being located
somehow as you suspect.

**Comment by nantonel** [comment]
In the [doc](https://1oly.github.io/AeroAcoustics.jl/dev/) I'd change `csm_file = joinpath(dirname(@__DIR__),"test","data","test1_csm.h5")` to something like:
```
csm_file = joinpath(replace(dirname(pathof(AeroAcoustics)),"src"=>"test"),"data","test1_csm.h5")
```
then I could run the code snippets except for `sourceintegration(x,E,int_region)`.

**Comment by 1oly** [comment]
Thanks @nantonel ! I will update accordingly. 
Please submit an issue for the sourceintegration error you got. Wonderful with the feedback :)

**Comment by 1oly** [comment]
Hi both,
Thanks for the comments and suggested change in the code. I have pushed #10 with some updates to the docs and example script. Hope you can run it now. 

Closing, but please reopen if the issue persist!
