### ISSUE TITLE
instructions to run test missing

### ISSUE THREAD

**Issue by thejasvibr** [1oly/AeroAcoustics.jl#8]
Hi, 
This is in relation to https://github.com/openjournals/joss-reviews/issues/6390.

There is a ```tests``` folder with scripts to run test, however there aren't any instructions on how to setup the tests and run them. A separate Markdown file either in the home folder or in the ```tests``` folder would be great.

**Comment by 1oly** [comment]
Hi, just pushed #10 with clarifications in the README on how to run tests. It's available on the master branch, will tag it later. Closing. Feel free to open the issue again if it is not clear.
