### ISSUE TITLE
[Docs] Source integration - undefined `x`

### ISSUE THREAD

**Issue by nantonel** [1oly/AeroAcoustics.jl#9]
In this [doc section](https://1oly.github.io/AeroAcoustics.jl/dev/#Source-integration-1) `x` is not defined in the code snippet. If an example can be given I think it would improve the docs. Thanks

Related to review: https://github.com/openjournals/joss-reviews/issues/6390

**Comment by 1oly** [comment]
Thanks for the comment !

This should be clarified with #10 
It's currently on master, will tag it later. Feel free to open another issue, if it is still not clear.
